// GLM-5.3-Flash W3 gate — the DSA indexer's k-pool compression and its ragged
// tail, against the RUN output of `transformers` v5.16.1.
//
// Row MODEL-MM-glm5-next-glm5-next-for-conditional-generation, issue #2213,
// `.agents/specs/glm5-next-flash.md` section W3.
//
// ─── WHAT MAKES THIS FIXTURE ABLE TO FAIL ───────────────────────────────────
//
// Three properties, each chosen because dropping it makes the whole file a
// tautology that a wrong port passes:
//
//  1. `seq_len` 21 is STRICTLY GREATER than `index_topk` 8. At or below
//     `index_topk` a top-k over raw tokens selects EVERYTHING, the selection is
//     the identity, and the pooling is unobservable. `.agents/specs/
//     glm5-next-flash.md` makes running past that threshold a requirement, not
//     a note, and the campaign's sibling row already paid for the same trap.
//  2. Row 1 is LEFT-PADDED by three tokens, so its pool grid starts at token 3.
//     A port that pools from slot 0 passes row 0 and fails row 1.
//  3. Selection error is BIMODAL, not continuous: the top-k either picks the
//     right pool or a completely different one, and the OUTPUT values of a
//     wrong-but-adjacent pool can be arbitrarily close. So this file asserts
//     SET EQUALITY of the selected indices and PRINTS THE MARGIN; a tolerance
//     on the values alone passes a wrong selection whose values happen to agree.
//     The fixture is tie-free by construction and the smallest margin over its
//     17 discriminating rows is reported by the case below.
//
// ─── THE ORACLE ─────────────────────────────────────────────────────────────
// `glm5_next_dsa_goldens.inc` is GENERATED by
// `fixtures/gen_glm5_next_dsa_goldens.py`, which RUNS the unmodified
// `Glm5NextTextIndexer` at transformers v5.16.1 — the lane revision W0 (#2096)
// recorded — through its own `__call__` and its own public sub-methods. Nothing
// in it is transcribed from our C++.
#include <doctest/doctest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

#include <fstream>

#include "glm5_next_dsa_goldens.inc"
#include "nlohmann/json.hpp"
#include "vllm/model_executor/models/glm5_next.h"
#include "vllm/model_executor/models/glm5_next_dsa.h"
#include "vllm/transformers_utils/hf_config.h"

namespace g = glm5_next_dsa_goldens;
using vllm::glm5_next::AppendVisibleTail;
using vllm::glm5_next::GetPooledStates;
using vllm::glm5_next::GetVisibleTokens;
using vllm::glm5_next::IndexerDims;
using vllm::glm5_next::IndexerDimsFrom;
using vllm::glm5_next::IndexerSelection;
using vllm::glm5_next::IndexerWeights;
using vllm::glm5_next::PackIndexerStates;
using vllm::glm5_next::PooledStates;
using vllm::glm5_next::SelectIndexerTopk;

namespace {

template <typename T, size_t N>
std::vector<T> Vec(const T (&a)[N]) {
  return std::vector<T>(a, a + N);
}

std::vector<uint8_t> Bytes(const int32_t* a, size_t n) {
  std::vector<uint8_t> v(n);
  for (size_t i = 0; i < n; ++i) v[i] = a[i] != 0 ? 1 : 0;
  return v;
}

IndexerDims FixtureDims() {
  IndexerDims d;
  d.hidden_size = g::kHidden;
  d.q_lora_rank = g::kQLora;
  d.n_heads = g::kNHeads;
  d.head_dim = g::kHeadDim;
  d.index_topk = g::kIndexTopk;
  d.index_kpool = g::kIndexKpool;
  d.always_select_tail = true;
  return d;
}

IndexerWeights FixtureWeights() {
  IndexerWeights w;
  w.wq_b = g::kWqB;
  w.wk = g::kWk;
  w.k_norm_weight = g::kKNormWeight;
  w.k_norm_bias = g::kKNormBias;
  w.weights_proj = g::kWeightsProj;
  w.kpool_ape = g::kKpoolApe;
  w.kpool_gate = g::kKpoolGate;
  return w;
}

std::vector<float> Hidden() { return Vec(g::kHiddenStates); }
std::vector<float> QResid() { return Vec(g::kQResid); }
std::vector<uint8_t> Mask() {
  return Bytes(g::kMask, static_cast<size_t>(g::kBatch * g::kSeqLen));
}

// The REAL published `config.json`, the same verbatim fixture the W1 scaffold
// gate reads. Its `index_kpool` is 4.
vllm::HfConfig PublishedConfig() {
  const std::string path = std::string(GLM5_NEXT_CKPT_FIXTURE_DIR) + "/config.json";
  std::ifstream in(path);
  REQUIRE_MESSAGE(in.good(), "missing fixture: " << path);
  return vllm::ParseHfConfig(nlohmann::json::parse(in), path);
}

// The set of REAL token indices a row selects. -1 is the invalid sentinel and
// duplicates are possible (upstream absorbs them with `scatter_add_` + `ne(0)`),
// so a set is the right comparison and a positionwise one would be stricter than
// the model's own semantics. The positionwise check is done separately below.
std::set<int32_t> SelectedSet(const int32_t* row, int64_t width) {
  std::set<int32_t> s;
  for (int64_t i = 0; i < width; ++i) {
    if (row[i] >= 0) s.insert(row[i]);
  }
  return s;
}

}  // namespace

TEST_CASE("glm5_next DSA: the fixture runs PAST index_topk, so the selection is not the identity") {
  // The property the whole file rests on, asserted rather than assumed. If a
  // later edit shrinks the fixture below `index_topk` every other case in this
  // file silently stops testing anything.
  REQUIRE(g::kSeqLen > g::kIndexTopk);
  const IndexerDims d = FixtureDims();
  // `select_k = min(index_topk // index_kpool, P)` = min(2, 5) = 2 of 5 pools.
  CHECK(d.SelectK(g::kNumPools) == 2);
  CHECK(d.SelectK(g::kNumPools) < g::kNumPools);
  // The tail widens the row past `index_topk`: 8 + 4 - 1 = 11.
  CHECK(d.OutputWidth() == g::kOutputWidth);
  CHECK(d.OutputWidth() == g::kIndexTopk + g::kIndexKpool - 1);
}

TEST_CASE("glm5_next DSA: the pooled candidate set matches the reference") {
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const std::vector<float> packed =
      PackIndexerStates(d, w, Hidden(), Mask(), g::kBatch, g::kSeqLen);

  const PooledStates p = GetPooledStates(d, w, packed, g::kBatch, g::kSeqLen);
  // `keep = pool_valid.any(0)` drops the pool no row can use, so P is 5 and not
  // ceil(21 / 4) = 6.
  REQUIRE(p.num_pools == g::kNumPools);

  for (int64_t b = 0; b < g::kBatch; ++b) {
    for (int64_t i = 0; i < p.num_pools; ++i) {
      CHECK(static_cast<int>(p.pool_valid[static_cast<size_t>(b * p.num_pools + i)]) ==
            g::kPoolValid[b * g::kNumPools + i]);
      for (int64_t j = 0; j < g::kIndexKpool; ++j) {
        const size_t o = static_cast<size_t>((b * p.num_pools + i) * g::kIndexKpool + j);
        CHECK(p.pool_indices[o] == g::kPoolIndices[o]);
      }
      for (int64_t c = 0; c < g::kHeadDim; ++c) {
        const size_t o = static_cast<size_t>((b * p.num_pools + i) * g::kHeadDim + c);
        // ABSOLUTE difference, not doctest::Approx: Approx carries a scale term
        // with a ~1.19e-5 floor, which would swallow a wrong pool weighting on
        // these small values.
        CHECK(std::abs(p.pool_keys[o] - g::kPoolKeys[o]) < 2e-5f);
      }
    }
  }
}

TEST_CASE("glm5_next DSA: the pool grid starts at the FIRST VALID token, not at slot 0") {
  // Row 1 is left-padded by three. Its first pool is therefore {3,4,5,6} and not
  // {0,1,2,3}, which is `get_pooled_states`' whole reason for computing
  // `first_key` (modular_glm5_next.py:938-945).
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const std::vector<float> packed =
      PackIndexerStates(d, w, Hidden(), Mask(), g::kBatch, g::kSeqLen);
  const PooledStates p = GetPooledStates(d, w, packed, g::kBatch, g::kSeqLen);
  const int64_t K = g::kIndexKpool;
  CHECK(p.pool_indices[0] == 0);
  CHECK(p.pool_indices[static_cast<size_t>(p.num_pools * K)] ==
        static_cast<int32_t>(g::kPadRow1));
  // and the two rows therefore do NOT share a grid.
  CHECK(p.pool_indices[0] != p.pool_indices[static_cast<size_t>(p.num_pools * K)]);
}

TEST_CASE("glm5_next DSA: visibility is causal AND padding-aware") {
  const std::vector<uint8_t> mask = Mask();
  const std::vector<uint8_t> vis =
      GetVisibleTokens(mask, g::kBatch, g::kSeqLen, g::kSeqLen, g::kSeqLen);
  REQUIRE(vis.size() == static_cast<size_t>(g::kBatch * g::kSeqLen * g::kSeqLen));
  for (size_t i = 0; i < vis.size(); ++i) {
    CHECK(static_cast<int>(vis[i]) == g::kVisible[i]);
  }
}

TEST_CASE("glm5_next DSA: the index SCORES match the reference, so a wrong SCALE cannot hide behind the argmax") {
  // WHY THIS CASE EXISTS. Everything else in this file gates the score chain
  // through the DISCRETE top-k, whose error is bimodal, and the margin printed
  // by the case below is computed from OUR OWN `sel.index_scores` — so it scales
  // WITH a scale defect rather than against it. Two live defects therefore
  // survived the whole file:
  //
  //   * `glm5_next_dsa.cpp` dropping `n_heads**-0.5` from the per-head mix
  //     (`:827`) — every score off by sqrt(8), relative error 1.83;
  //   * `IndexerDims::softmax_scale()` built from the WRONG head dim — relative
  //     error 1.0, which is exactly the trap `glm5_next_dsa.h` warns about in
  //     prose ("this is the INDEXER head dim, not the MLA one"). Prose does not
  //     gate.
  //
  // Both are uniform positive rescalings, so they permute NOTHING: the argmax,
  // the selected set and the positionwise indices are all unchanged. Only the
  // VALUES move, and only this case reads them.
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const IndexerSelection sel =
      SelectIndexerTopk(d, w, Hidden(), QResid(), Mask(), g::kBatch, g::kSeqLen);
  REQUIRE(sel.index_scores.size() ==
          static_cast<size_t>(g::kBatch * g::kSeqLen * g::kNumPools));

  double worst = 0.0;
  double biggest = 0.0;
  for (size_t i = 0; i < sel.index_scores.size(); ++i) {
    // ABSOLUTE difference, not doctest::Approx, for the same reason the
    // `pool_keys` check above uses one: Approx carries a scale term with a
    // ~1.19e-5 floor.
    //
    // THE TOLERANCE, and why it is both loose and tight. Measured worst
    // difference on this fixture is 7.63e-6, against a largest |golden| of
    // 45.17 — one f32 ULP at that magnitude, from the left-padded query rows.
    // 2e-4 is 26x that headroom, so reduction-order drift cannot make it flaky.
    // It is still tight against the defect it is here for: a UNIFORM relative
    // scale error r moves the largest value by r * 45.17, so this reds for any
    // r above 4.4e-6. Both surviving defects are r = 1.0 and r = 1.83.
    CHECK(std::abs(sel.index_scores[i] - g::kIndexScores[i]) < 2e-4f);
    worst = std::max(worst, std::abs(static_cast<double>(sel.index_scores[i]) -
                                     static_cast<double>(g::kIndexScores[i])));
    biggest = std::max(biggest, std::abs(static_cast<double>(g::kIndexScores[i])));
  }
  MESSAGE("index_scores: worst absolute difference = " << worst << " over " << sel.index_scores.size()
                                                       << " values, largest |golden| = " << biggest);
}

TEST_CASE("glm5_next DSA: the selection matches the reference, by SET, with a printed margin") {
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const IndexerSelection sel =
      SelectIndexerTopk(d, w, Hidden(), QResid(), Mask(), g::kBatch, g::kSeqLen);
  REQUIRE(sel.topk_indices.size() ==
          static_cast<size_t>(g::kBatch * g::kSeqLen * g::kOutputWidth));
  REQUIRE(sel.pooled.num_pools == g::kNumPools);

  const int64_t P = g::kNumPools, K = g::kIndexKpool, W = g::kOutputWidth;
  const int64_t select_k = d.SelectK(P);
  double worst_margin = 1e300;
  int discriminating = 0;

  for (int64_t b = 0; b < g::kBatch; ++b) {
    for (int64_t s = 0; s < g::kSeqLen; ++s) {
      const int32_t* got = sel.topk_indices.data() + (b * g::kSeqLen + s) * W;
      const int32_t* want = g::kTopkIndices + (b * g::kSeqLen + s) * W;

      // SET equality of the real token indices — the assertion a bimodal error
      // cannot slip past.
      const std::set<int32_t> gs = SelectedSet(got, W);
      const std::set<int32_t> ws = SelectedSet(want, W);
      CHECK(gs == ws);
      // and positionwise too, because upstream's layout — selection, then the
      // raw tail, then the -1 padding — is what the downstream mask builder
      // scatters over.
      for (int64_t i = 0; i < W; ++i) CHECK(got[i] == want[i]);

      // The MARGIN: the gap between the last SELECTED candidate's score and the
      // best REJECTED one, over the valid candidates for this query.
      std::vector<std::pair<float, int64_t>> cands;
      for (int64_t p = 0; p < P; ++p) {
        const int32_t last = g::kPoolIndices[(b * P + p) * K + K - 1];
        const int64_t safe = last < 0 ? 0 : (last >= g::kSeqLen ? g::kSeqLen - 1 : last);
        const bool vis = g::kVisible[(b * g::kSeqLen + s) * g::kSeqLen + safe] != 0;
        if (vis && g::kPoolValid[b * P + p] != 0) {
          cands.emplace_back(sel.index_scores[static_cast<size_t>((b * g::kSeqLen + s) * P + p)],
                             p);
        }
      }
      if (static_cast<int64_t>(cands.size()) <= select_k) continue;
      ++discriminating;
      std::sort(cands.begin(), cands.end(),
                [](const auto& a, const auto& c) { return a.first > c.first; });
      const double margin = static_cast<double>(cands[static_cast<size_t>(select_k) - 1].first) -
                            static_cast<double>(cands[static_cast<size_t>(select_k)].first);
      // A ZERO margin is a tie, and a tie makes the set equality above a coin
      // flip rather than a measurement. The fixture is built to have none.
      CHECK(margin > 0.0);
      worst_margin = std::min(worst_margin, margin);
    }
  }
  // Enough rows where the top-k actually had to choose. Below this the file is
  // measuring the identity again.
  CHECK(discriminating >= 17);
  MESSAGE("k-pool selection: " << discriminating
                               << " discriminating rows, smallest margin = " << worst_margin);
  // The recorded floor, so a future edit that collapses the fixture's separation
  // reds here instead of silently making every set comparison a tie.
  CHECK(worst_margin > 2e-3);
}

TEST_CASE("glm5_next DSA: the ragged tail is appended RAW and UNSCORED") {
  // `index_kpool_always_select_tail` widens the row to `index_topk + kpool - 1`
  // and the appended indices are the current incomplete pool's tokens, which the
  // top-k never scored. Truncating to `index_topk` drops them.
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const IndexerSelection sel =
      SelectIndexerTopk(d, w, Hidden(), QResid(), Mask(), g::kBatch, g::kSeqLen);
  const int64_t W = g::kOutputWidth;
  // Row 0, query 0: nothing is selectable (no pool's last member is visible yet)
  // and the tail is the single visible token 0.
  const int32_t* r00 = sel.topk_indices.data();
  for (int64_t i = 0; i < g::kIndexTopk; ++i) CHECK(r00[i] == -1);
  CHECK(r00[g::kIndexTopk] == 0);

  // The padded query rows of row 1 are ALL -1 (`:873`).
  for (int64_t s = 0; s < g::kPadRow1; ++s) {
    const int32_t* r = sel.topk_indices.data() + (g::kSeqLen + s) * W;
    for (int64_t i = 0; i < W; ++i) CHECK(r[i] == -1);
  }

  // AppendVisibleTail is a NO-OP at kpool 1, which is upstream's own early
  // return; the tail width is `kpool - 1`.
  IndexerDims one = d;
  one.index_kpool = 1;
  const std::vector<int32_t> in(static_cast<size_t>(g::kBatch * g::kSeqLen * 4), 7);
  const std::vector<uint8_t> vis(
      static_cast<size_t>(g::kBatch * g::kSeqLen * g::kSeqLen), 1);
  const std::vector<uint8_t> vk(static_cast<size_t>(g::kBatch * g::kSeqLen), 1);
  CHECK(AppendVisibleTail(one, in, 4, vis, vk, g::kBatch, g::kSeqLen, g::kSeqLen) == in);
}

TEST_CASE("glm5_next DSA: a sequence with NO complete pool is SERVED, not refused") {
  // A prompt shorter than `index_kpool` — or a left-padded row with fewer than
  // `index_kpool` valid tokens — has no complete pool. `pool_valid` is then all
  // zero, `keep = pool_valid.any(0)` is empty (`modular_glm5_next.py:967-970`),
  // P is 0, `select_k = min(index_topk // index_kpool, 0)` is 0, and the pooled
  // selection is EMPTY. Upstream does not refuse this state: `append_visible_
  // tail` still returns the raw visible tail, so the row is served with a
  // tail-only selection. We used to `Require(P > 0, ...)` and THROW, which
  // refused four prompts the oracle answers — the first four tokens of every
  // short prefill.
  //
  // The goldens below are the RUN output of the same unmodified
  // `Glm5NextTextIndexer` at transformers v5.16.1, so this asserts the SELECTION
  // and not merely that nothing throws.
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const int64_t W = g::kOutputWidth;
  REQUIRE(g::kShortCases == 4);

  int64_t off = 0;
  for (int64_t c = 0; c < g::kShortCases; ++c) {
    const int64_t S = g::kShortSeqLen[c];
    const int64_t pad = g::kShortPad[c];
    CAPTURE(c);
    CAPTURE(S);
    CAPTURE(pad);
    // The property that makes the case the one it claims to be.
    REQUIRE(S - pad < g::kIndexKpool);

    const std::vector<float> hidden(g::kShortHidden + off * g::kHidden,
                                    g::kShortHidden + (off + S) * g::kHidden);
    const std::vector<float> qres(g::kShortQResid + off * g::kQLora,
                                  g::kShortQResid + (off + S) * g::kQLora);
    const std::vector<uint8_t> mask = Bytes(g::kShortMask + off, static_cast<size_t>(S));

    const IndexerSelection sel = SelectIndexerTopk(d, w, hidden, qres, mask, 1, S);
    // The empty-pool path is the one actually taken, and the oracle agrees it
    // is empty. Without this the case could pass on a fixture that still pools.
    CHECK(sel.pooled.num_pools == 0);
    CHECK(sel.pooled.num_pools == g::kShortNumPools[c]);
    // `select_k` is 0 and the whole output width is therefore tail plus padding.
    CHECK(d.SelectK(sel.pooled.num_pools) == 0);

    REQUIRE(sel.topk_indices.size() == static_cast<size_t>(S * W));
    for (int64_t i = 0; i < S * W; ++i) {
      CAPTURE(i);
      CHECK(sel.topk_indices[static_cast<size_t>(i)] == g::kShortTopk[off * W + i]);
    }
    off += S;
  }
  // Every value in the block was consumed, so a golden that grew without the
  // loop growing with it reds here instead of going unread.
  CHECK(off * W == static_cast<int64_t>(sizeof(g::kShortTopk) / sizeof(g::kShortTopk[0])));
}

TEST_CASE("glm5_next DSA: `index_kpool` is READ, and the value CHANGES the answer") {
  // The config side of this is pinned in test_glm5_next_scaffold.cpp (4 on the
  // published checkpoint, 16 as the class default). This is the BEHAVIOURAL half:
  // the resolved value reaches the indexer, and a different one produces a
  // different selection — so a reader that defaults instead of reading is not a
  // cosmetic defect, it selects other tokens.
  const IndexerDims d = FixtureDims();
  const IndexerWeights w = FixtureWeights();
  const IndexerSelection four =
      SelectIndexerTopk(d, w, Hidden(), QResid(), Mask(), g::kBatch, g::kSeqLen);

  IndexerDims two = d;
  two.index_kpool = 2;  // still divides index_topk 8, so it is a LEGAL config
  const IndexerSelection other =
      SelectIndexerTopk(two, w, Hidden(), QResid(), Mask(), g::kBatch, g::kSeqLen);
  CHECK(two.OutputWidth() != d.OutputWidth());
  CHECK(other.topk_indices != four.topk_indices);
  CHECK(other.pooled.num_pools != four.pooled.num_pools);

  // And the resolved published config carries 4, straight through to the dims
  // the indexer runs on — not the config class's 16.
  const vllm::Glm5NextParams p = vllm::ParseGlm5NextParams(PublishedConfig());
  const IndexerDims from_cfg = IndexerDimsFrom(p);
  CHECK(from_cfg.index_kpool == 4);
  CHECK(from_cfg.index_kpool != 16);
  CHECK(from_cfg.index_topk == 2048);
  CHECK(from_cfg.SelectK(1 << 20) == 512);
  CHECK(from_cfg.OutputWidth() == 2051);
}

TEST_CASE("glm5_next DSA: the geometry group is refused BY NAME when it is incoherent") {
  IndexerDims d = FixtureDims();
  d.index_kpool = 0;
  CHECK_THROWS_WITH_AS(d.Validate(), doctest::Contains("`index_kpool` must be >= 1"),
                       std::invalid_argument);
  d = FixtureDims();
  d.index_kpool = 3;  // 8 % 3 != 0
  CHECK_THROWS_WITH_AS(d.Validate(), doctest::Contains("must be divisible by `index_kpool`"),
                       std::invalid_argument);
  d = FixtureDims();
  d.q_lora_rank = 0;
  CHECK_THROWS_WITH_AS(d.Validate(), doctest::Contains("q_lora_rank"), std::invalid_argument);
}
